-- ═══════════════════════════════════════════════════════════════
-- DeskMatch — Core Service: Tabla WorkspaceAttributes
-- ═══════════════════════════════════════════════════════════════
-- Crear la tabla de atributos dinamicos y ajustar columnas
-- necesarias para la entidad Workspace (Rating, ReviewCount, etc.)
-- -----------------------------------------------------------------
-- Correr UNA SOLA VEZ en el servidor:
--   docker exec -i deskmatch-postgres psql -U deskmatch -d deskmatch_core < postgres/migrate-dynamic-attributes.sql
-- ═══════════════════════════════════════════════════════════════

BEGIN;

-- 1. Tabla de atributos dinamicos
CREATE TABLE IF NOT EXISTS core."WorkspaceAttributes" (
    "WorkspaceId" uuid NOT NULL,
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Key" character varying(64) NOT NULL,
    "Value" character varying(256),
    CONSTRAINT "PK_WorkspaceAttributes" PRIMARY KEY ("WorkspaceId", "Id"),
    CONSTRAINT "FK_WorkspaceAttributes_Workspaces_WorkspaceId" FOREIGN KEY ("WorkspaceId")
        REFERENCES core."Workspaces" ("Id") ON DELETE CASCADE
);

-- 2. Agregar columnas Rating y ReviewCount (si no existen)
DO $$ BEGIN
    ALTER TABLE core."Workspaces" ADD COLUMN "Rating" double precision;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE core."Workspaces" ADD COLUMN "ReviewCount" integer NOT NULL DEFAULT 0;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;

COMMIT;

