-- ═══════════════════════════════════════════════════════════════
-- DeskMatch — Core Service Migration Fix
-- ═══════════════════════════════════════════════════════════════
-- Las tablas ya existen en la DB (creadas antes de EF migrations).
-- Este script marca las migraciones previas como aplicadas y crea
-- la nueva tabla WorkspaceAttributes.
-- -----------------------------------------------------------------
-- Correr UNA SOLA VEZ en el servidor:
--   docker exec -i deskmatch-postgres psql -U deskmatch -d deskmatch_core < infrastructure/docker/postgres/migrate-dynamic-attributes.sql
-- ═══════════════════════════════════════════════════════════════

BEGIN;

-- 1. Marcar migraciones previas como aplicadas
INSERT INTO core."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260531142033_InitialCore', '8.0.8')
ON CONFLICT DO NOTHING;

INSERT INTO core."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260602011547_AddWorkspace', '8.0.8')
ON CONFLICT DO NOTHING;

-- 2. Crear tabla WorkspaceAttributes
CREATE TABLE IF NOT EXISTS core."WorkspaceAttributes" (
    "WorkspaceId" uuid NOT NULL,
    "Id" integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "Key" character varying(64) NOT NULL,
    "Value" character varying(256),
    CONSTRAINT "PK_WorkspaceAttributes" PRIMARY KEY ("WorkspaceId", "Id"),
    CONSTRAINT "FK_WorkspaceAttributes_Workspaces_WorkspaceId" FOREIGN KEY ("WorkspaceId")
        REFERENCES core."Workspaces" ("Id") ON DELETE CASCADE
);

-- 3. Modificar columnas existentes (de AddDynamicAttributes migration)
-- Estas modificaciones son seguras si las columnas ya tienen el tipo correcto
ALTER TABLE core."Workspaces" ALTER COLUMN "Name" TYPE character varying(256);
ALTER TABLE core."Workspaces" ALTER COLUMN "City" TYPE character varying(128);
ALTER TABLE core."Workspaces" ALTER COLUMN "Country" TYPE character varying(128);
ALTER TABLE core."Workspaces" ALTER COLUMN "Address" TYPE character varying(512);
ALTER TABLE core."Workspaces" ALTER COLUMN "Capacity" SET DEFAULT 1;
ALTER TABLE core."Workspaces" ALTER COLUMN "PricePerHour" TYPE numeric(10,2);
ALTER TABLE core."Workspaces" ALTER COLUMN "PricePerDay" TYPE numeric(10,2);
ALTER TABLE core."Workspaces" ALTER COLUMN "PricePerMonth" TYPE numeric(10,2);
ALTER TABLE core."Workspaces" ALTER COLUMN "CreatedAt" SET DEFAULT NOW();
ALTER TABLE core."Workspaces" ALTER COLUMN "IsActive" SET DEFAULT TRUE;

-- 4. Agregar columnas nuevas (si no existen)
DO $$ BEGIN
    ALTER TABLE core."Workspaces" ADD COLUMN "Rating" double precision;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;

DO $$ BEGIN
    ALTER TABLE core."Workspaces" ADD COLUMN "ReviewCount" integer NOT NULL DEFAULT 0;
EXCEPTION WHEN duplicate_column THEN NULL;
END $$;

-- 5. Marcar la migración AddDynamicAttributes como aplicada
INSERT INTO core."__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260608003604_AddDynamicAttributes', '8.0.8')
ON CONFLICT DO NOTHING;

COMMIT;
